### ISSUE TITLE
generatedChannelApk error , please check it and fix it ，and that you should generate all  Channel Apk again!

### ISSUE THREAD

**Issue by mylogo1024** [ltlovezh/ApkChannelPackage#173]
ApkSectionInfo = lowMemory : false
 apkSize : 435577463
 contentEntry : first = java.nio.HeapByteBuffer[pos=0 lim=435060736 cap=435060736] , second = 0
 schemeV2Block : first = java.nio.HeapByteBuffer[pos=0 lim=4096 cap=4096] , second = 435060736
 centralDir : first = java.nio.HeapByteBuffer[pos=0 lim=512609 cap=512609] , second = 435064832
 eocd : first = java.nio.HeapByteBuffer[pos=0 lim=22 cap=22] , second = 435577441
generatedChannelApk , channel = fuck_you , apkChannelName = 7336_new_zipalign_sign_c.apk
generateApkSigningBlock , needPadding = true
generateApkSigningBlock , final length = 4088 padding = 370 bufferSize = 358
addIdValueByteBufferMap , oldApkSigningBlock size = 4096 , newApkSigningBlock size = 4096
generatedChannelApk error , please check it and fix it ，and that you should generate all  Channel Apk again!
java.io.FileNotFoundException: D:\app_c.apk (拒绝访问。)
        at java.base/java.io.RandomAccessFile.open0(Native Method)
        at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:354)
        at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:271)
        at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:221)
        at com.tencent.vasdolly.writer.IdValueWriter.addIdValueByteBufferMap(IdValueWriter.java:148)
        at com.tencent.vasdolly.writer.IdValueWriter.addIdValue(IdValueWriter.java:52)
        at com.tencent.vasdolly.writer.ChannelWriter.addChannelByV2(ChannelWriter.java:68)
        at com.tencent.vasdolly.command.Util.generateChannelApk(Util.java:279)
        at com.tencent.vasdolly.command.Util.writeChannel(Util.java:119)
        at com.tencent.vasdolly.command.Main.main(Main.java:177)
------ File 7336_new_zipalign_sign.apk generate channel apk , end ------
------ total 1 channel apk , cost : 406 ------

**Comment by 3bearsoft** [comment]
遇到了同样的问题，output指定为apk时会失败，但指定为目录则没问题

**Comment by chenxing890** [comment]
一样的问题，  不能指定输出文件名， 只能指定目录。   官方示例有毒
